services:
  - type: web
    name: fpt-healthcare-api
    env: java
    plan: free
    branch: main
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/fpt-healthcare-api-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-morning-salad-a10ikcsq-pooler.ap-southeast-1.aws.neon.tech/fpthealth?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_b92GILPjYeMq
